### ISSUE TITLE
Inverted Scrolling

### ISSUE THREAD

**Issue by chopmann** [Generation0/NephelinClient#5]
@Generation0 
Should the scrolling be inverted: I press the left mouse button and move the pointer up and the map moves down.

or

I press the left mouse button and move the pointer up and the map moves up?

If you dont press the mouse button is a more "intuitive" kind of movement. With the mouse button pressed what most people  expect is "inverted" movement.

**Comment by tloeb** [comment]
@chopmann like GoogleMaps... i press the left mouse btn and the map moves to the top

**Comment by chopmann** [comment]
@Generation0 ok. Then we need a different mouse pointer, like the one from googleMaps. Can you look for an implementation?

**Comment by tloeb** [comment]
@chopmann when map is moved, cursor also is changed to a "move" cursor
https://github.com/Generation0/NephelinClient/tree/scroll_cursor

Also css foundation is now included to gulp
